### ISSUE TITLE
present at Argo Workflows community meeting

### ISSUE THREAD

**Issue by alexec** [couler-proj/couler#165]
please come and present

we will record

you can share the recording - get more users

**Comment by merlintang** [comment]
I think Terry would like to present this work.

**Comment by terrytangyuan** [comment]
Actually I have presented to Argo community meeting previously. See the link to slides here: https://github.com/couler-proj/couler#community-blogs-and-presentations

If anyone else is interested in presenting, please let us know here or reach out to us directly. cc @couler-proj/couler-team 

In the meantime, @alexec mentioned earlier that we could contribute a guest blogpost on Argo Medium. I'll see if we could find some time to work on that soon at some point.

**Comment by alexec** [comment]
I'd love another presentation!

I've quietly posted this: https://blog.argoproj.io/authoring-and-submitting-argo-workflows-using-python-aff9a070d95f

I want us to promote Couler more as the go-to solution for Python with Argo Workflows. 

Would you like to take a look at that post and propose changes?

https://github.com/argoproj-labs/argo-client-gen

**Comment by terrytangyuan** [comment]
Thanks. I'll take a look at the post and comment in the Google Doc you shared earlier.

**Comment by terrytangyuan** [comment]
BTW, is the Medium link you posted permanent? If so, would you like to add the link to https://github.com/couler-proj/couler#community-blogs-and-presentations?

**Comment by alexec** [comment]
I think the URL is permanent. We can tweak or change the content.
