### ISSUE TITLE
container volumeMounts can not mount exsist PVC.

### ISSUE THREAD

**Issue by peiniliu** [couler-proj/couler#193]
## Summary 

What happened/what you expected to happen?

We expect the container use the existing volume defined inside the workflow. Such as:
[volumes-existing.yaml](https://github.com/argoproj/argo-workflows/blob/master/examples/volumes-existing.yaml)

example for testing:
````
import os

import couler.argo as couler
from couler.argo_submitter import ArgoSubmitter
from couler.core.templates.volume import VolumeMount, Volume

couler.add_volume(Volume("apppath", "mnist"))

mount = VolumeMount("apppath", "/data/")
command = ["ls", mount.mount_path]

couler.run_container(
        image="alpine:3.12.0", command=command, volume_mounts=[mount]
    )

submitter = ArgoSubmitter(namespace="testagent")
couler.run(submitter=submitter)
````

OrderedDict([('apiVersion', 'argoproj.io/v1alpha1'), ('kind', 'Workflow'), ('metadata', {'generateName': 'runpy-'}), ('spec', {'entrypoint': 'runpy', **'volumes': [OrderedDict([('name', 'apppath'), ('persistentVolumeClaim', {'claimName': 'mnist'})]**)], 'templates': [{'name': 'runpy', 'steps': [[OrderedDict([('name', 'module-3418'), ('template', 'module')])]]}, OrderedDict([('name', 'module'), ('container', OrderedDict([('image', 'alpine:3.12.0'), ('command', ['ls', '/data/']), ('volumeMounts', [OrderedDict([('name', 'apppath'), ('mountPath', '/data/')])])])), (**'volumes', [{'name': 'apppath', 'emptyDir': {}}**])])]})])

This will raise the problem because the volumeMounts inside the container find volumes inside the container('emptyDir') rather than volumes inside the workflow(PVC).

The reason is this code, because inside the container, automatically generate volumes for volumeMounts,

https://github.com/couler-proj/couler/blob/d20f874882e55c5e3aa53ffaf78670f6b4d314a0/couler/core/templates/container.py#L146-L153

After removing the automatically generated 'emptydir{}', the volumeMount point to the right volume definition inside the workflow.

OrderedDict([('apiVersion', 'argoproj.io/v1alpha1'), ('kind', 'Workflow'), ('metadata', {'generateName': 'runpy-'}), ('spec', {'entrypoint': 'runpy', **'volumes': [OrderedDict([('name', 'apppath'), ('persistentVolumeClaim', {'claimName': 'mnist'}**)])], 'templates': [{'name': 'runpy', 'steps': [[OrderedDict([('name', 'module-3418'), ('template', 'module')])]]}, OrderedDict([('name', 'module'), ('container', OrderedDict([('image', 'alpine:3.12.0'), ('command', ['ls', '/data/']), ('volumeMounts', [OrderedDict([('name', 'apppath'), ('mountPath', '/data/')])])])), (**'volumes', [])**])]})])

## Diagnostics

What is the version of Couler you are using? 

latest v0.1.1rc8

What is the version of the workflow engine you are using?

argo: v3.0.0-rc3

Any logs or other information that could help debugging?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Thanks for reporting! Your diagnosis sounds correct. We should probably only generate those emptyDir volumes when needed. Would you like to submit a PR to fix it?

**Comment by knagarajan1984** [comment]
Hi,
I am facing the same issue too. Any idea when this is planned to be fixed?

**Comment by terrytangyuan** [comment]
It's work-in-progress in https://github.com/couler-proj/couler/pull/194.

**Comment by peiniliu** [comment]
> @peiniliu
> I am facing the same issue too. Any idea when this is planned to be fixed?

Hi,

yes, it is WIP. 
if it is urgent, you could temporarily try my branch https://github.com/peiniliu/couler. 
installation: pip install git+https://github.com/peiniliu/couler.git

Peini

**Comment by nooraangelva** [comment]
> > @peiniliu
> > I am facing the same issue too. Any idea when this is planned to be fixed?
> 
> Hi,
> 
> yes, it is WIP.
> if it is urgent, you could temporarily try my branch https://github.com/peiniliu/couler.
> installation: pip install git+https://github.com/peiniliu/couler.git
> 
> Peini

Thank you for the temporary fix. I have been struggling with this for several days.

Noora

**Comment by terrytangyuan** [comment]
It’s merged now. Please give it a try. Thanks @peiniliu for the fix!
