### ISSUE TITLE
Create a documentation website?

### ISSUE THREAD

**Issue by dinever** [couler-proj/couler#198]
# Summary

Couler needs more documentation. See #100 and #101

Maybe we should have a website to organize core syntax & examples, hosted under http://couler-proj.github.io? We can use [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/insiders/).

I'm happy to take on this if we think it's a good idea. Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by merlintang** [comment]
good idea @dinever , please give it a try and send a PR. Thanks for your contribution.

**Comment by terrytangyuan** [comment]
dba
