### ISSUE TITLE
Dependencies not supporting map()

### ISSUE THREAD

**Issue by nooraangelva** [couler-proj/couler#206]
## Summary 

What happened/what you expected to happen?

I expected Couler to produce something similar to this [yaml code](https://github.com/argoproj/argo-workflows/blob/master/examples/dag-diamond-steps.yaml) with the code [couler code](https://github.com/nooraangelva/ArgoWorkflowsToCouler/blob/main/map_diamond.py)

## Diagnostics

What is the version of Couler you are using? 

I downloaded Couler again two days ago.

What is the version of the workflow engine you are using?

Any logs or other information that could help debugging?

Result in Argo UI:

![image](https://user-images.githubusercontent.com/78410623/119960654-78ac5100-bfa5-11eb-83f7-3531d9fb8331.png)

yaml:

![image](https://user-images.githubusercontent.com/78410623/119961031-e2c4f600-bfa5-11eb-9e30-e9c50ba18948.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by nooraangelva** [comment]
> You've hard-coded your `step_name` in `echo_xx()` functions.

Hi, 

I updated the code [Couler code](https://github.com/nooraangelva/ArgoWorkflowsToCouler/blob/main/map_diamond.py).
It still has the same problem. Would you or anyone have tips on how to write the code. I have only recently started working with Couler so it is still a mystery for me. (Right now I am trying to turn Argo example-workflows to Coulers format.)

Thanks in advance.

**Comment by moshewe** [comment]
merged #215
