### ISSUE TITLE
Install instructions don't work in Pycharm `venv`

### ISSUE THREAD

**Issue by moshewe** [couler-proj/couler#208]
## Summary 

I'm working with a PyCharm generated `venv` (3.8.5) and running install scripts supplied here doesn't work. The folder in `site-packages` has no real code in it.

When I run it from a normal terminal, that is Python 3.8.5 sans `venv`, it install an `egg`.
I don't think this is expected behaviour - I was expecting a wheel...

## Diagnostics

Mac BigSur 11.3.1
Latest repository version `0.1.1rc8`.

**Comment by terrytangyuan** [comment]
Have you tried installing other packages too?

**Comment by moshewe** [comment]
Yes, other packages work.
I've tried cloning the repo and installing using `python setup.py install` and I get the following error:
`error: chardet 4.0.0 is installed but chardet<4.0,>=2.0 is required by {'aiohttp'}`

**Comment by moshewe** [comment]
Running `pip install git+https://github.com/couler-proj/couler.git` works, I can see the package installed when I run `pip list | grep couler`, but when I look at the `site-packages` I still see the PyPi package... 

A simple fix would be to publish the package under SOME name in PyPi, I guess...

**Comment by moshewe** [comment]
When I start a python interpreter from the `venv`, I can import `couler` properly. This is weird.

**Comment by terrytangyuan** [comment]
This is probably an issue with `venv` itself and not related to this project. I don't have experience with `venv` so I'd suggest you to seek advice from other sources.

**Comment by moshewe** [comment]
Putting `git+http://github.com/couler-proj/couler` in `requirements.txt` and running `pip install -r requirement.txt` solved it!

**Comment by terrytangyuan** [comment]
Good to know. Thanks1
