### ISSUE TITLE
volumeClaimTemplates accessModes could support other options than just [ "ReadWriteOnce" ]

### ISSUE THREAD

**Issue by nooraangelva** [couler-proj/couler#210]
# Summary

What change needs making?

![image](https://user-images.githubusercontent.com/78410623/121495491-f1fe6780-c9d9-11eb-89b4-e354aacd1d26.png)

Accesmode and storage could be made by the workflows creator so there wouldn't be just the default options.

# Use Cases

When would you use this?

If I need bigger `storage` or smaller or if I need to use `ReadWriteMany` as `accessMode`.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Yes this is a valid use case that's currently unsupported. Would you like to submit a PR?

**Comment by nooraangelva** [comment]
Sure.
