### ISSUE TITLE
Setting a default `Submitter`

### ISSUE THREAD

**Issue by moshewe** [couler-proj/couler#213]
# Summary

Currently, every time we submit a workflow we call `couler.run(submitter)`. I think that setting a default `submitter` and also exposing a getter/setter for it would make code more readable and is more intuitive, as it's not probable the same process will use multiple `Submitter`s. The original `couler.run(submitter)` will remain.

# Use Cases

When setting up a Python program that launches workflows, assuming it doesn't switch `submitter`s a lot.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Sounds good. Feel free to submit a PR.

**Comment by moshewe** [comment]
merged.
