### ISSUE TITLE
Implement a default workflow name "salt"

### ISSUE THREAD

**Issue by moshewe** [couler-proj/couler#219]
# Summary

Automated scripts might submit multiple workflows under the same name. This creates a naming conflict and rejects any workflow but the first. Implementing a "salt" for workflow names, e.g. create a random suffix for workflow names, would make sure the naming clash won't happen/

# Use Cases

Differentiate between different runs of the same workflow by workflow name at the very minimum.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by merlintang** [comment]
good point, if you do not mind, we are so welcome your or.

**Comment by moshewe** [comment]
merged in #216
