### ISSUE TITLE
Drop efforts to support more than Argo as a workflow engine

### ISSUE THREAD

**Issue by moshewe** [couler-proj/couler#230]
# Summary

Make a decision.
Code changes are minimal.

# Use Cases

Dissimilarities between workflow engines will make the codebase more complicated, and we are having difficulty getting code contributions as is. Focusing on one engine will give the project more focus and attract more users.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by terrytangyuan** [comment]
The other engines are actually not supported yet. There are existing issues to track the progress.
