### ISSUE TITLE
Is Couler dead?

### ISSUE THREAD

**Issue by dmerrick** [couler-proj/couler#251]
# Summary

The marketing for couler is great... it convinced my company to use it. Unfortunately it seems like this project is no longer under development. The "multiple backend" feature that is the primary reason to use couler appears to be missing... even though Airflow is mentioned several times in the docs, it's [not supported](https://github.com/couler-proj/couler/issues/43) and there appears to be no progress on it.

Right now the only thing couler does is build Argo workflows. If someone were to be choosing an Argo workflow generation tool, [Hera](https://github.com/argoproj-labs/hera-workflows) seems like a better choice because it's officially supported and it's far easier to understand the code.

Also, the documentation for couler is lacking. The examples like DAG and coin-flip are nice, but that's basically everything a developer has to work with. I can't tell you how many times I've gone back to those examples looking to answer a question I had and been disappointed. I've had to dig through the tests to get examples of important features like Artifacts.

Sure, these issues are fixable. But who is going to fix them?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Thank you for your contributions so far and your thoughts. I've added a note at the top of the README to reflect the status. https://github.com/couler-proj/couler/pull/252
