### ISSUE TITLE
CronWorkflow support?

### ISSUE THREAD

**Issue by Mastergalen** [couler-proj/couler#253]
# Summary

What change needs making?

Support for submitting CronWorkflows via Couler

# Use Cases

I am currently using Argo CronWorkflows to run nightly or weekly pipelines. I would like to use Couler to help submit new CronWorkflows after making changes to my pipeline. Even better if Couler can help delete my old CronWorkflows.

At the moment I think it's possible for me to generate the workflow yaml in Couler and then retrieving the workflow yaml with `couler.workflow_yaml()`. Then I would need to manually wrap it with the necessary yaml structure to make it a CronWorkflow.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by merlintang** [comment]
https://github.com/couler-proj/couler/blob/master/couler/tests/cron_workflow_test.py#L30

yes cronworkflow is supported, please check this example.

**Comment by Mastergalen** [comment]
Ah I missed that, thanks!
