### ISSUE TITLE
Cannot install couler package 

### ISSUE THREAD

**Issue by kyle-google** [couler-proj/couler#266]
## Summary 
I am unable to make any progress using couler after installing the python package and running the example: https://github.com/couler-proj/couler/blob/master/examples/default_submitter.py. 

Getting issues on "couler is not a pacakge". 

What happened/what you expected to happen?
Expected `python3 -m pip install git+https://github.com/couler-proj/couler --ignore-installed` to work.
## Diagnostics

What is the version of Couler you are using? 
```
python3 -m pip show couler
Name: couler
Version: 0.1.1rc8
Summary: Unified Interface for Constructing and Managing Workflows
Home-page: 
Author: 
Author-email: 
License: 
Location: /Users/kylesorensen/Library/Python/3.9/lib/python/site-packages
Requires: Deprecated, docker, kubernetes, pyaml, stringcase, StringGenerator
Required-by:
```

What is the version of the workflow engine you are using?
N/A, but quay.io/argoproj/workflow-controller:v3.4.8

Any logs or other information that could help debugging?
Traceback (most recent call last):
  File "/Users/kylesorensen/src/automlops/couler.py", line 1, in <module>
    import couler.argo as couler
  File "/Users/kylesorensen/src/automlops/couler.py", line 1, in <module>
    import couler.argo as couler
ModuleNotFoundError: No module named 'couler.argo'; 'couler' is not a package
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Rename your couler.py to something else and try again.

**Comment by terrytangyuan** [comment]
Also check which python you are using for your script

**Comment by kyle-google** [comment]
Changing that couler.py to couler-test.py fixed it... thanks @terrytangyuan!

Hadn't thought the naming of the file would affect the package I am trying import... 🤦‍♂️
