### ISSUE TITLE
Add utility method to convert boolean to to "true"/"false"

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#29]
There are cases where we need to convert boolean to strings "true"/"false" that can be used in YAML configuration. We can create a utility method for this. An example here: https://github.com/couler-proj/couler/blob/9e177e97b5338f034f8b99e90e65a511af37a721/couler/core/templates/job.py#L40

**Comment by xfate123** [comment]
@terrytangyuan  can I contribute something for this issue? Still need couple more days to finish reading the source code, after that I think I can contribute some to this issue

**Comment by terrytangyuan** [comment]
Sure, feel free to pick up any of the existing issues to work on.
