### ISSUE TITLE
Move all import statements to top of the files

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#30]
Per PEP8
> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.

There are currently cases where import statements are inside the functions, e.g. https://github.com/couler-proj/couler/blob/9e177e97b5338f034f8b99e90e65a511af37a721/couler/core/templates/output.py#L51-L58

**Comment by arez3002** [comment]
Hi @terrytangyuan 
May i work on this issue ?

**Comment by merlintang** [comment]
sure, thanks for your contribution.

**Comment by arez3002** [comment]
Thank you for letting me work on the subject.
I think I have to write a python file that first separates the imports from the rest of the code and put them to txt files, and then it would be able to add the two txt files along with a blank line between them, and then it would be better to remove the txt files at the end.

**Comment by terrytangyuan** [comment]
@arez30002 Why would you need Python and text files? This issue is simply than what you expected: just moving all imports to the top of the files manually.

**Comment by arez30002** [comment]
I thought you needed a program for this; it's no problem I use the same program and I make all the inputs.

**Comment by arez30002** [comment]
I'm sorry I don't think I can continue the project; please ask someone else to do it.
