### ISSUE TITLE
Support multiple function arguments in `couler.map()`

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#32]
We currently only support one argument in `couler.map()`, which is a list of values that can be called by the specified function.

https://github.com/couler-proj/couler/blob/fedbcc42383eb3335d3fadddf818defcf74d70a4/couler/core/syntax/loop.py#L23-L32

**Comment by reprabhala** [comment]
@terrytangyuan  can I pick this up as well?

**Comment by terrytangyuan** [comment]
Sure
