### ISSUE TITLE
Support Apache Airflow as a backend

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#43]
This issue is for discussing adding Apache Airflow as a backend in Couler that's consistent with the design proposed in https://github.com/couler-proj/couler/pull/24. 

If you are interested in contributing, please comment and share your proposals below. Once we agree on a concrete implementation plan, we can then split this into multiple issues so more people can get involved.

**Comment by d4l3k** [comment]
@terrytangyuan is there any timeline/plans for this? project lists Airflow in the tag line so I was surprised to not see any support for it

**Comment by terrytangyuan** [comment]
So far it looks like there isn't any interest from the community so I doubt that there is any timeline for this unless a dedicated contributor wants to work on it.

**Comment by dmerrick** [comment]
Maybe make that clear in the docs for the project? At my company we picked couler because we thought it supported Airflow, but if it's only argo it feels like https://github.com/argoproj-labs/hera-workflows might be a better choice

**Comment by merlintang** [comment]
@terrytangyuan  we can discuss the way to implement for supporting couler for airflow recently. @dmerrick , can you propose what is your requirement more clearly?  We start this part once we have a clear requirement.

**Comment by dmerrick** [comment]
We went with Couler because we thought it supported both Airflow and Argo. I don't have any specific requirements other than a functional `AirflowSubmitter`

**Comment by merlintang** [comment]
Thanks for your updating. @dmerrick Let us figure a dev plan to support this. I went through the current way to run Airflow over K8s, it is not that easy to use.

**Comment by misteliy** [comment]
Just wanted to plus one here since my team is leveraging argo but other teams in the company are using airflow. To have a common framework would be really great indeed.

**Comment by dmerrick** [comment]
If this is **not planned**, it might be a good idea to remove Airflow from the README

**Comment by terrytangyuan** [comment]
I added a disclaimer in the README a while back:
> Couler currently only supports Argo Workflows as the workflow orchestration backend

Unfortunately I don't have permission to make further updates since the project is owned by my previous employer.
