### ISSUE TITLE
Re-enable workflow YAML validation

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#49]
Currently `couler.run()`'s workflow YAML validation is commented out: https://github.com/couler-proj/couler/blob/412ea049e8fb0f749cebbdc5eff45b365bd85ac9/couler/argo.py#L60-L61

We'd like to enable this back once a stable argo-client-python is released.

cc @binarycrayon

**Comment by binarycrayon** [comment]
K will follow up here once we got an updated release published to pypi :-)
