### ISSUE TITLE
Interested in the project

### ISSUE THREAD

**Issue by xinbinhuang** [couler-proj/couler#5]
Hi @terrytangyuan @merlintang,

I have been evaluating different workflow systems (e.g. Airflow, Argo, Kubeflow, Dagster) recently but haven't seen to find anything really appealing to me - I was thinking to use Argo, but really likely that I need to build some layer on top of it. 

As I came across this project, the description `Unified Interface for Constructing and Managing Workflows` really catch my eyes. There are so many tools these days, and I think it will needs some unification. I wonder what's the goal of this project and what's your vision of `Unified Interface`? 

I would definitely like to learn more and contribute to it.

Cheers,
Bin

**Comment by terrytangyuan** [comment]
@xinbinhuang Thanks for your interest! We actually just open sourced this project yesterday. We are still migrating and cleaning up the codebase and putting together the initial working version that will work with Argo Workflows. One of the goals is indeed to provide a unified interface for multiple workflow engines. Please stay tuned once we have a clearly defined API and then community members are more than welcomed to help support other workflow engines.

**Comment by xinbinhuang** [comment]
Hi @terrytangyuan, I am closing this issue now as we have some discussion offline.
