### ISSUE TITLE
Remove the customized utility function for workflow YAML validation

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#50]
Currently we have a utility function for validating the workflow YAML used for Argo backend in [workflow_validation_utils.py](https://github.com/couler-proj/couler/blob/412ea049e8fb0f749cebbdc5eff45b365bd85ac9/couler/core/workflow_validation_utils.py). This is necessary currently since the existing release of Argo Python client v3.2.0 has issues when de-serializing an `argo.workflows.client.modelsV1alpha1Template` object and we have to validate specs and templates individually.

This is not ideal as the underlying schema might change as Argo gets upgraded. We should check whether the same issue exists when the new version of Argo Python client is ready and aim to reuse whatever is available.

cc @binarycrayon

**Comment by jamindy** [comment]
您好，已收到您的邮件，我会尽快给您回复。
