### ISSUE TITLE
Move argo-workflows to optional dependency

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#68]
Currently `argo-workflows` is part of `requirements.txt` that will be installed as a required package (see `install_requires` field in `setup.py`). We should move it to extra/optional requirements instead.

**Comment by reprabhala** [comment]
@terrytangyuan can I pick this up?

**Comment by terrytangyuan** [comment]
Definitely. Currently it's only used for [workflow validation](https://github.com/couler-proj/couler/blob/master/couler/core/workflow_validation_utils.py). We should make it optional and then only validate the workflow when `argo-workflows` is available.

**Comment by reprabhala** [comment]
Thanks! 👍
Do you have any recommendations on the best way to test this? I was wondering if just verifying the packages installed with "python -m pip install -r requirements.txt" and "python -m pip install -r requirements-dev.txt" separately will suffice?

**Comment by terrytangyuan** [comment]
That should be sufficient as long as CI passes.

**Comment by terrytangyuan** [comment]
Close via https://github.com/couler-proj/couler/pull/164
