### ISSUE TITLE
Copyright notices are missing for some Python scripts

### ISSUE THREAD

**Issue by terrytangyuan** [couler-proj/couler#99]
We have good coverage on copyright notices at the top of each files in https://github.com/couler-proj/couler/tree/d34a690/couler/core but many are still missing, for example:

* https://github.com/couler-proj/couler/tree/d34a690/couler/steps
* https://github.com/couler-proj/couler/tree/d34a690/couler/tests

**Comment by reprabhala** [comment]
@terrytangyuan, can I pick this up?

**Comment by terrytangyuan** [comment]
Yes definitely

**Comment by reprabhala** [comment]
Thanks @terrytangyuan! Unable to push to the repo to raise a PR right now. Would you be able to help me with this?

**Comment by terrytangyuan** [comment]
You would need to push to your forked repo and then submit a PR from there: https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo
